### ISSUE TITLE
Replace all Icons8 icons with icons from The Noun Project

### ISSUE THREAD

**Issue by Joltrix** [StarcounterApps/Timeline#29]
We do not have an Icons8 license, while we do have a license on [The Noun Project](https://thenounproject.com/)

**Comment by andwah** [comment]
I will supply the needed icons in svg format (from The Nonu Project)

**Comment by Joltrix** [comment]
Okay, perfect! :)

**Comment by Joltrix** [comment]
Have been fixed and pushed to develop as of this [PR](https://github.com/StarcounterApps/Timeline/pull/35)
