### ISSUE TITLE
CSS Themes for blended views

### ISSUE THREAD

**Issue by Joltrix** [StarcounterApps/Timeline#31]
I'm not exactly sure where to create this issue, but since Timeline is one of the apps that blends with many, I created it here (for now).

Yesterday I was discussing how to create theming, both for indvidual apps and for blended views like inside.starcounter.com, or other similar views with @andwah.

We were discussing the use of css variables, and somehow structuring the apps to adhere by these variables. So if we at some point want to change the coloration, we could easily do it from one place.

### Individual Apps
What's the best approach to this? Should we create variables for all the "main colors", and then use these throughout the app?

For example
"`--primary-app-color: #262626;`"
and then reuse that variable everywhere we need that color? (even though it's a button, or a div background, or a text color)

Or is it better to kinda give each "element type" its own variable.

"`--button-primary: #262626;`"
"`--button-secondary: #252525;`"
etc.

Or maybe both

"`--primary-app-color: #262626;`"

"`--button-primary: var(--primary-app-color);`"
"`--list-highlight: var(--primary-app-color);`"

### Blended Views
And how we do this but on a bigger scale, and apply these variables to all of the apps inside a blended view?

Could adding them to one of the "wrapping" apps work? Like, adding a stylesheet to launchpad, or website app, or to the composition editor, which could "spread" its styling to all the other apps? Or would this go against the "starcounter way" of making apps?

But then again, if we choose to do it like this, won't all of the apps need to adhere by the naming from the wrapper app that holds the variable?

Cause one of the goals for the future is also to make these themes easily "adjustable", so that we can have different themes, that will apply to the whole composition of apps.

cc @andwah @warpech @tomalec @miyconst @bouguila

**Comment by bouguila** [comment]
Regarding the styling of the in apps individually it is not an issue since the use of variables is already a good way of imposing some general CSS rules, but the styling of the blended views is another more complicated story as if we impose styles they could conflict with the rules of the app itself.

**Comment by tomalec** [comment]
That's a long-lasting problem.
We already made an app to manage CSS Variables https://github.com/StarcounterApps/CssVariablesManager

In general, I'd say CSS Custom Properties (Variables) are the Starcounter-way, I think we just lack good examples, cases, and experience in such theming. Today we had a discussion with @warpech (https://github.com/Starcounter/RebelsLounge/issues/75#issuecomment-331137496)

We would like to create a good example of theming at https://github.com/StarcounterApps/KitchenSink/issues/172

Please note that it's vital to specify theming problem precisely. As for example simple Bootstraps `button{ width: anyvaluepx}` is definitely not a "global theme" you need, as most probably it would make an app with hundreds of buttons (Palma?) look unusable.

Therefore I'd say the shadow dom encapsulation is a benefit here, as you can/have to specify the theme for each root separately.

> But then again, if we choose to do it like this, won't all of the apps need to adhere by the naming from the wrapper app that holds the variable?

I'd rather avoid any "wrapper apps" and use just regular HTML compositions (data filled in DB) for that. Note that you can use one variable to set a different variable in different host:
```css
.foo>::slotted(starcounter-include){
    --bar-prop: var(--baz-prop);
}
```

I'd keep this discussion in RebelsLounge, as it's in Starcounter's org, and affects all other apps.

**Comment by warpech** [comment]
As @tomalec said, [RebelsLounge](https://github.com/Starcounter/RebelsLounge) is the issue tracker relevant to ask these questions. Anyway thanks for bringing this up.

Yes, CSS Variables are the way to go. Starcounter will implement own CSS "unframework" called `Underwear.css` that is explained in https://github.com/Starcounter/RebelsLounge/issues/75#issuecomment-346792791 which utilizes CSS Variables.

Your question in "Individual Apps" is very good. I made a check how other CSS frameworks implement variables of various kinds:

- [Bootstrap implements your solution 1](https://github.com/twbs/bootstrap/blob/991cbe74d0004f443fc14c748dd1d8da424d7dde/_data/theme-colors.yml)
- [Turret implements your solution 2](https://github.com/turretcss/turretcss/blob/6f2705d16813fa4f1f9fbd2edeb466c92498281f/turret/element/button-colors.css)
- [Materialize implements your solution 3](https://github.com/Dogfalo/materialize/blob/c25dfe2fdd5fe64d3e3b55dafa39515c6745e829/sass/components/_variables.scss)
- [Bulma implements your solution 3](https://github.com/jgthms/bulma/blob/38057310e88b0763c57e9ae14ae126ac633a4e8b/sass/utilities/derived-variables.sass)
- [MCW implements your solution 1](https://github.com/material-components/material-components-web/blob/49cd750ed5dbd13312e19ad235c4c571252ddd36/packages/mdc-theme/_variables.scss)

In `Underwear.css` are starting with the solution 1. Unless proven insufficient, I think this is the correct choice according to the Occam's razor. If we need more granularity, we can upgrade to solution 3 anytime.

> Could adding them to one of the "wrapping" apps work? Like, adding a stylesheet to launchpad, or website app, or to the composition editor, which could "spread" its styling to all the other apps? Or would this go against the "starcounter way" of making apps?

As always, we should avoid dependency between the apps. It is much better to depend on global Starcounter CSS Variables if anything. This is the approach that we are taking in `Underwear.css`. As explained in https://github.com/Starcounter/RebelsLounge/issues/75#issuecomment-348955423, there will be a ColorThemer app that stores custom `Underwear.css` variable values and applies them by middleware.

I hope this answers the question. Do you have a case in which CSS Variables are already used that I should be aware of?

If possible, please respond in https://github.com/Starcounter/RebelsLounge/issues/75. Closing this issue as I would prefer to track this problem in a single place.
