### ISSUE TITLE
Filters for timeline are not visible in smaller resolution

### ISSUE THREAD

**Issue by PatrykSzwer** [StarcounterApps/Timeline#33]
When You open filters in window with small resolution (or decrease resolution after opening it) You have no possibility to see and change filters. See screen below:

![image](https://user-images.githubusercontent.com/25042256/30646756-5aa03fec-9e1a-11e7-98b4-85c3b20ae610.png)

This modal view should be responsive or at least there should be some scroll to be able to see full content of filters window.

**Comment by Joltrix** [comment]
Thanks for reporting! I'll get right on it! :D

**Comment by Joltrix** [comment]
Have been fixed and pushed to develop as of this [PR](https://github.com/StarcounterApps/Timeline/pull/35)
