### ISSUE TITLE
Create a TeamCity job for Timeline

### ISSUE THREAD

**Issue by Joltrix** [StarcounterApps/Timeline#39]

**Comment by ubbeK** [comment]
Just gave @Joltrix admin access for all Apps project on TeamCity. Lets sit down and fix this together.

**Comment by Joltrix** [comment]
The teamcity jobs for Timeline and Notes are upp and running :) thanks @ubbeK for all the help :D

Closing this one, if we want to make any changes to the teamcity projects, we can create new issues
